# Generated by Django 4.1.7 on 2023-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=15)),
                ('scannerID', models.CharField(max_length=50)),
            ],
        ),
    ]
