# Generated by Django 4.1.7 on 2023-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendancerecord_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=15)),
                ('group', models.CharField(max_length=3)),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=5)),
                ('roomNo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ScannerRoom',
            fields=[
                ('scannerID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('roomID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('cardID', models.CharField(max_length=50)),
                ('name', models.TextField(max_length=50)),
                ('age', models.IntegerField()),
                ('section', models.CharField(max_length=15)),
                ('group', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='uid',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='cardID',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
